<?php
$minicart_presets =  array(
	'oxy-ou_cart' => array(
		json_decode(
			
			'{
				"name":"Default","slug":"minicart-default","options":{"original":{"oxy-ou_cart_cntsp_padding_padding-top":"0","oxy-ou_cart_cntsp_padding_padding-left":"8","oxy-ou_cart_cntsp_padding_padding-right":"8","oxy-ou_cart_cntsp_padding_padding-bottom":"8","oxy-ou_cart_-widget-shopping-cart-content_border_border-top-style":"solid","oxy-ou_cart_-widget-shopping-cart-content_border_border-right-style":"solid","oxy-ou_cart_-widget-shopping-cart-content_border_border-bottom-style":"solid","oxy-ou_cart_-widget-shopping-cart-content_border_border-left-style":"solid","oxy-ou_cart_-widget-shopping-cart-content_border_border-top-width":"1","oxy-ou_cart_-widget-shopping-cart-content_border_border-right-width":"1","oxy-ou_cart_-widget-shopping-cart-content_border_border-bottom-width":"1","oxy-ou_cart_-widget-shopping-cart-content_border_border-left-width":"1","oxy-ou_cart_-widget-shopping-cart-content_border_border-top-color":"#e5e5e5","oxy-ou_cart_-widget-shopping-cart-content_border_border-right-color":"#e5e5e5","oxy-ou_cart_-widget-shopping-cart-content_border_border-bottom-color":"#e5e5e5","oxy-ou_cart_-widget-shopping-cart-content_border_border-left-color":"#e5e5e5","oxy-ou_cart_btncontainer_margin_margin-bottom":"0","oxy-ou_cart_itemimg_margin_margin-bottom":"0","oxy-ou_cart_itemimg_padding_padding-top":"2","oxy-ou_cart_itemimg_padding_padding-left":"2","oxy-ou_cart_itemimg_padding_padding-right":"2","oxy-ou_cart_itemimg_padding_padding-bottom":"2","oxy-ou_cart_slug_ulcartlistliimgulproductlistwidgetliimg_border_color":"#e8e8e8","oxy-ou_cart_slug_ulcartlistliimgulproductlistwidgetliimg_border_width":"1","oxy-ou_cart_slug_minicartitemaremovesvg_color":"#afafaf","oxy-ou_cart_slug_minicartitemaremovehoversvg_color":"#000000","oxy-ou_cart_mcitem_padding_padding-top":"8","oxy-ou_cart_mcitem_padding_padding-bottom":"14","oxy-ou_cart_slug_ulproductlistwidgetli_margin_bottom":"3","oxy-ou_cart_ouocc_prdpfs":"12","oxy-ou_cart_ouocc_prdplblfs":"12","oxy-ou_cart_slug_minicartitempricelabel_text_transform":"uppercase","oxy-ou_cart_ouocc_prdpfw":"400","oxy-ou_cart_slug_minicartitemaremove_right":"0"}}
			}', 
			true 
		),

		json_decode(

			'{
				"name":"Cart Items Only", "slug": "cart-items-only","options":{"original":{"oxy-ou_cart_disable_sbrow":"Yes","oxy-ou_cart_disable_ntrow":"Yes","oxy-ou_cart_itemimg_margin_margin-bottom":"0","oxy-ou_cart_slug_minicartitemaremove_right":"0","oxy-ou_cart_slug_minicartitempricelabel_margin_top":"4","oxy-ou_cart_ouocc_prdplblfs":"12","oxy-ou_cart_ouocc_prdpfs":"12","oxy-ou_cart_slug_minicartitempricelabel_text_transform":"uppercase","oxy-ou_cart_ouocc_prdpc":"#8c8c8c","oxy-ou_cart_slug_ulproductlistwidgetliminicartitem_border_width":"0","oxy-ou_cart_slug_widgetshoppingcartcontent_background_color":"#efefef","oxy-ou_cart_slug_ulproductlistwidgetlinthchildodd_background_color":"#ffffff","oxy-ou_cart_slug_ulproductlistwidgetlinthchildeven_background_color":"#ffffff","oxy-ou_cart_slug_ulproductlistwidgetli_margin_bottom":"1"}}
			}',
			true
		),

		json_decode(
			
			'{
				"name":"With Coupon Form","slug":"with-coupon-form","options":{"original":{"oxy-ou_cart_itemimg_margin_margin-bottom":"0","oxy-ou_cart_itemimg_padding_padding-top":"2","oxy-ou_cart_itemimg_padding_padding-left":"2","oxy-ou_cart_itemimg_padding_padding-right":"2","oxy-ou_cart_itemimg_padding_padding-bottom":"2","oxy-ou_cart_slug_ulcartlistliimgulproductlistwidgetliimg_border_color":"#e8e8e8","oxy-ou_cart_slug_ulcartlistliimgulproductlistwidgetliimg_border_width":"1","oxy-ou_cart_slug_minicartitemaremovesvg_color":"#afafaf","oxy-ou_cart_slug_minicartitemaremovehoversvg_color":"#f90000","oxy-ou_cart_mcitem_padding_padding-top":"8","oxy-ou_cart_mcitem_padding_padding-bottom":"14","oxy-ou_cart_slug_ulproductlistwidgetli_margin_bottom":"0","oxy-ou_cart_ouocc_prdpfs":"12","oxy-ou_cart_ouocc_prdplblfs":"12","oxy-ou_cart_slug_minicartitempricelabel_text_transform":"uppercase","oxy-ou_cart_ouocc_prdpfw":"400","oxy-ou_cart_coupon_form_enable":"Yes","oxy-ou_cart_slug_ulproductlistwidgetliminicartitem_border_color":"#f2f2f2","oxy-ou_cart_-ouocc-coupon-field_border_border_radius_border-radius":"0","oxy-ou_cart_-wc-notice-text_typography_font-size":"12","oxy-ou_cart_-oucc-coupon-label_typography_color":"#3dc100","oxy-ou_cart_-oucc-coupon-label_typography_font-weight":"400","oxy-ou_cart_-oucc-discount-price- -oucc-discount-price -woocommerce-Price-amount_typography_color":"#3dc100","oxy-ou_cart_-order-total-row -order-total-label_typography_color":"#ffffff","oxy-ou_cart_-order-total-row -order-total-price- -order-total-price -woocommerce-Price-amount_typography_color":"#ffffff","oxy-ou_cart_slug_aouoccremovecouponsvg_color":"#fc0202","oxy-ou_cart_slug_aouoccremovecouponhoversvg_color":"#000000","oxy-ou_cart_-wc-notice-text_typography_line-height":"1.3","oxy-ou_cart_slug_couponbtnhover_background_color":"#fc0000","oxy-ou_cart_slug_minicartitemaremove_top-unit":"%","oxy-ou_cart_cc_padding_padding-left":"8","oxy-ou_cart_cc_padding_padding-right":"8","oxy-ou_cart_slug_ouoccqty_background_color":"rgba(0,0,0,0)","oxy-ou_cart_slug_minicartitempricelabel_margin_top":"10","oxy-ou_cart_slug_minicartitemaremove_right":"0","oxy-ou_cart_slug_ordertotalrow_background_color":"#ff0202","oxy-ou_cart_-order-total-row_border_border-top-style":"none","oxy-ou_cart_-order-total-row_border_border-right-style":"none","oxy-ou_cart_-order-total-row_border_border-bottom-style":"none","oxy-ou_cart_-order-total-row_border_border-left-style":"none","oxy-ou_cart_ottl_padding_padding-top":"8","oxy-ou_cart_ottl_padding_padding-left":"12","oxy-ou_cart_ottl_padding_padding-right":"12","oxy-ou_cart_ottl_padding_padding-bottom":"8"},"hover":{"oxy-ou_cart_slug_couponbtnbackground_color":"#fc0000"}}
			}',
			true
		)
	)
);