<?php

$menucart_presets = array(
	'oxy-ou_minicart' => array(
		json_decode(
			'{
				"name":"Default","slug":"default","options":{"original":{"oxy-ou_minicart_oumc_btnt":"icon","oxy-ou_minicart_oumc_ict":"icon","oxy-ou_minicart_oumc_btnicon":"FontAwesomeicon-shopping-basket","oxy-ou_minicart_bubble_ptop":"8","oxy-ou_minicart_bubble_pright":"-8","oxy-ou_minicart_cart_preview":"Disable","oxy-ou_minicart_oumc_wrapper":"320","oxy-ou_minicart_mccontainer_padding_padding-top":"22","oxy-ou_minicart_mccontainer_padding_padding-left":"30","oxy-ou_minicart_mccontainer_padding_padding-right":"30","oxy-ou_minicart_mccontainer_padding_padding-bottom":"19","oxy-ou_minicart_mcitem_padding_padding-bottom":"10","oxy-ou_minicart_oumc_sepclr":"#dddddd","oxy-ou_minicart_remove_clr":"#7f7f7f","oxy-ou_minicart_remove_ptop":"3","oxy-ou_minicart_oumc_imgAlign":"Left","oxy-ou_minicart_oumc_titlemb":"3","oxy-ou_minicart_-mini-cart-item a_typography_color":"#7a7a7a","oxy-ou_minicart_oumc_titlehc":"#000000","oxy-ou_minicart_oumc_prdqtyc":"#848484","oxy-ou_minicart_oumc_qtyfs":"12","oxy-ou_minicart_oumc_prdpc":"#878585","oxy-ou_minicart_oumc_prdpfs":"13","oxy-ou_minicart_oumc_prdpfw":"400","oxy-ou_minicart_price_clr":"#f40000","oxy-ou_minicart_mcsubt_margin_margin-top":"8","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-horizontal-offset":"0","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-vertical-offset":"0","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-blur":"16","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-color":"#e2e2e2","oxy-ou_minicart_remove_pright-unit":"%","oxy-ou_minicart_oumc_wrappermat":"30","oxy-ou_minicart_oumc_wrappermrt":"100","oxy-ou_minicart_oumc_wrappermrt-unit":"%","oxy-ou_minicart_oumc_wrappermlt":"-144","oxy-ou_minicart_remove_hc":"#ef0909","oxy-ou_minicart_cartbgns_width-unit":"%","oxy-ou_minicart_cartbgns_width":"100","oxy-ou_minicart_cartbgns_gap":"0","oxy-ou_minicart_cartbgns_gaptop":"10","oxy-ou_minicart_btn_align":"Left","oxy-ou_minicart_slug_ulcartlistliimgulproductlistwidgetliimg_border_width":"0","oxy-ou_minicart_itemimg_margin_margin-bottom":"0","oxy-ou_minicart_itemimg_margin_margin-top":"0","oxy-ou_minicart_oumc_prdimgw":"50","oxy-ou_minicart_remove_pright":"0","oxy-ou_minicart_mcitem_padding_padding-right":"20","oxy-ou_minicart_oumc_cprice":"no"},"media":{"phone-landscape":{"original":{"oxy-ou_minicart_oumc_wrappermlt":"-144","oxy-ou_minicart_oumc_wrappermrt-unit":"%","oxy-ou_minicart_oumc_wrappermrt":"100"}}}}
			}',
			true
		),

		json_decode(
			'{
				"name":"Vertical Buttons","slug":"vertical-buttons","options":{"original":{"oxy-ou_minicart_oumc_btnt":"icon","oxy-ou_minicart_oumc_ict":"icon","oxy-ou_minicart_oumc_btnicon":"FontAwesomeicon-shopping-basket","oxy-ou_minicart_bubble_ptop":"8","oxy-ou_minicart_bubble_pright":"-8","oxy-ou_minicart_cart_preview":"Disable","oxy-ou_minicart_oumc_wrapper":"320","oxy-ou_minicart_mccontainer_padding_padding-top":"22","oxy-ou_minicart_mccontainer_padding_padding-left":"30","oxy-ou_minicart_mccontainer_padding_padding-right":"30","oxy-ou_minicart_mccontainer_padding_padding-bottom":"19","oxy-ou_minicart_mcitem_padding_padding-bottom":"10","oxy-ou_minicart_oumc_sepclr":"#dddddd","oxy-ou_minicart_remove_clr":"#7f7f7f","oxy-ou_minicart_remove_ptop":"3","oxy-ou_minicart_oumc_imgAlign":"Right","oxy-ou_minicart_remove_pleft":"0","oxy-ou_minicart_mcitem_padding_padding-left":"24","oxy-ou_minicart_oumc_titlemb":"3","oxy-ou_minicart_-mini-cart-item a_typography_color":"#7a7a7a","oxy-ou_minicart_oumc_titlehc":"#000000","oxy-ou_minicart_oumc_prdqtyc":"#848484","oxy-ou_minicart_oumc_qtyfs":"12","oxy-ou_minicart_oumc_prdpc":"#878585","oxy-ou_minicart_oumc_prdpfs":"13","oxy-ou_minicart_oumc_prdpfw":"400","oxy-ou_minicart_price_clr":"#f40000","oxy-ou_minicart_mcsubt_margin_margin-top":"8","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-horizontal-offset":"0","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-vertical-offset":"0","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-blur":"16","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-color":"#e2e2e2","oxy-ou_minicart_remove_pright-unit":"%","oxy-ou_minicart_remove_pright":"100","oxy-ou_minicart_oumc_wrappermat":"30","oxy-ou_minicart_oumc_wrappermrt":"100","oxy-ou_minicart_oumc_wrappermrt-unit":"%","oxy-ou_minicart_oumc_wrappermlt":"-150","oxy-ou_minicart_remove_hc":"#ef0909","oxy-ou_minicart_cartbgns_width-unit":"%","oxy-ou_minicart_cartbgns_width":"100","oxy-ou_minicart_cartbgns_gap":"0","oxy-ou_minicart_cartbgns_gaptop":"10","oxy-ou_minicart_btn_align":"Left","oxy-ou_minicart_slug_ulcartlistliimgulproductlistwidgetliimg_border_width":"0","oxy-ou_minicart_itemimg_margin_margin-bottom":"0","oxy-ou_minicart_itemimg_margin_margin-top":"0","oxy-ou_minicart_oumc_prdimgw":"50"},"media":{"phone-landscape":{"original":{"oxy-ou_minicart_oumc_wrappermlt":"-150","oxy-ou_minicart_oumc_wrappermrt-unit":"%","oxy-ou_minicart_oumc_wrappermrt":"100"}}}}
			}',
			true
		),

		json_decode(
			'{
				"name":"Vetical Buttons 2","slug":"vertical-buttons-2","options":{"original":{"oxy-ou_minicart_oumc_btnt":"icon","oxy-ou_minicart_oumc_ict":"icon","oxy-ou_minicart_oumc_btnicon":"FontAwesomeicon-shopping-basket","oxy-ou_minicart_bubble_ptop":"8","oxy-ou_minicart_bubble_pright":"-8","oxy-ou_minicart_cart_preview":"Disable","oxy-ou_minicart_oumc_wrapper":"320","oxy-ou_minicart_mccontainer_padding_padding-top":"22","oxy-ou_minicart_mccontainer_padding_padding-left":"30","oxy-ou_minicart_mccontainer_padding_padding-right":"30","oxy-ou_minicart_mccontainer_padding_padding-bottom":"19","oxy-ou_minicart_mcitem_padding_padding-bottom":"0","oxy-ou_minicart_oumc_sepclr":"#dddddd","oxy-ou_minicart_remove_clr":"#7f7f7f","oxy-ou_minicart_remove_ptop":"3","oxy-ou_minicart_oumc_imgAlign":"Right","oxy-ou_minicart_remove_pleft":"0","oxy-ou_minicart_mcitem_padding_padding-left":"24","oxy-ou_minicart_oumc_titlemb":"3","oxy-ou_minicart_-mini-cart-item a_typography_color":"#7a7a7a","oxy-ou_minicart_oumc_titlehc":"#000000","oxy-ou_minicart_oumc_prdqtyc":"#848484","oxy-ou_minicart_oumc_qtyfs":"12","oxy-ou_minicart_oumc_prdpc":"#878585","oxy-ou_minicart_oumc_prdpfs":"13","oxy-ou_minicart_oumc_prdpfw":"400","oxy-ou_minicart_price_clr":"#f40000","oxy-ou_minicart_mcsubt_margin_margin-top":"8","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-horizontal-offset":"0","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-vertical-offset":"0","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-blur":"16","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-color":"#e2e2e2","oxy-ou_minicart_remove_pright-unit":"%","oxy-ou_minicart_remove_pright":"100","oxy-ou_minicart_oumc_wrappermat":"30","oxy-ou_minicart_oumc_wrappermrt":"100","oxy-ou_minicart_oumc_wrappermrt-unit":"%","oxy-ou_minicart_oumc_wrappermlt":"-150","oxy-ou_minicart_remove_hc":"#ef0909"},"media":{"phone-landscape":{"original":{"oxy-ou_minicart_oumc_wrappermlt":"-150","oxy-ou_minicart_oumc_wrappermrt-unit":"%","oxy-ou_minicart_oumc_wrappermrt":"100"}}}}
			}
			',
			true
		),

		json_decode(
			'{
				"name":"Horizontal Buttons","slug":"horizontal-buttons","options":{"original":{"oxy-ou_minicart_oumc_btnt":"icon","oxy-ou_minicart_oumc_ict":"icon","oxy-ou_minicart_oumc_btnicon":"FontAwesomeicon-shopping-basket","oxy-ou_minicart_bubble_ptop":"8","oxy-ou_minicart_bubble_pright":"-8","oxy-ou_minicart_cart_preview":"Disable","oxy-ou_minicart_oumc_wrapper":"320","oxy-ou_minicart_mccontainer_padding_padding-top":"22","oxy-ou_minicart_mccontainer_padding_padding-left":"30","oxy-ou_minicart_mccontainer_padding_padding-right":"30","oxy-ou_minicart_mccontainer_padding_padding-bottom":"19","oxy-ou_minicart_mcitem_padding_padding-bottom":"0","oxy-ou_minicart_oumc_sepclr":"#dddddd","oxy-ou_minicart_remove_clr":"#7f7f7f","oxy-ou_minicart_remove_ptop":"3","oxy-ou_minicart_oumc_imgAlign":"Left","oxy-ou_minicart_oumc_titlemb":"3","oxy-ou_minicart_-mini-cart-item a_typography_color":"#7a7a7a","oxy-ou_minicart_oumc_titlehc":"#000000","oxy-ou_minicart_oumc_prdqtyc":"#848484","oxy-ou_minicart_oumc_qtyfs":"12","oxy-ou_minicart_oumc_prdpc":"#878585","oxy-ou_minicart_oumc_prdpfs":"13","oxy-ou_minicart_oumc_prdpfw":"400","oxy-ou_minicart_price_clr":"#f40000","oxy-ou_minicart_mcsubt_margin_margin-top":"8","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-horizontal-offset":"0","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-vertical-offset":"0","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-blur":"16","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-color":"#e2e2e2","oxy-ou_minicart_remove_pright-unit":"%","oxy-ou_minicart_oumc_wrappermat":"30","oxy-ou_minicart_oumc_wrappermrt":"100","oxy-ou_minicart_oumc_wrappermrt-unit":"%","oxy-ou_minicart_oumc_wrappermlt":"-150","oxy-ou_minicart_remove_hc":"#ef0909","oxy-ou_minicart_slug_ulcartlistliimgulproductlistwidgetliimg_border_width":"0","oxy-ou_minicart_remove_pright":"0","oxy-ou_minicart_mcitem_padding_padding-right":"24"},"media":{"phone-landscape":{"original":{"oxy-ou_minicart_oumc_wrappermlt":"-150","oxy-ou_minicart_oumc_wrappermrt-unit":"%","oxy-ou_minicart_oumc_wrappermrt":"100"}}}}
			}',
			true
		),

		json_decode(
			'{
				"name":"Cart Icon with Total Price","slug":"total-price","options":{"original":{"oxy-ou_minicart_oumc_btnt":"icon","oxy-ou_minicart_oumc_ict":"icon","oxy-ou_minicart_oumc_btnicon":"FontAwesomeicon-shopping-basket","oxy-ou_minicart_bubble_ptop":"8","oxy-ou_minicart_bubble_pright":"-8","oxy-ou_minicart_cart_preview":"Disable","oxy-ou_minicart_oumc_wrapper":"320","oxy-ou_minicart_mccontainer_padding_padding-top":"22","oxy-ou_minicart_mccontainer_padding_padding-left":"30","oxy-ou_minicart_mccontainer_padding_padding-right":"30","oxy-ou_minicart_mccontainer_padding_padding-bottom":"19","oxy-ou_minicart_mcitem_padding_padding-bottom":"10","oxy-ou_minicart_oumc_sepclr":"#dddddd","oxy-ou_minicart_remove_clr":"#7f7f7f","oxy-ou_minicart_remove_ptop":"3","oxy-ou_minicart_oumc_imgAlign":"Left","oxy-ou_minicart_oumc_titlemb":"3","oxy-ou_minicart_-mini-cart-item a_typography_color":"#7a7a7a","oxy-ou_minicart_oumc_titlehc":"#000000","oxy-ou_minicart_oumc_prdqtyc":"#848484","oxy-ou_minicart_oumc_qtyfs":"12","oxy-ou_minicart_oumc_prdpc":"#878585","oxy-ou_minicart_oumc_prdpfs":"13","oxy-ou_minicart_oumc_prdpfw":"400","oxy-ou_minicart_price_clr":"#f40000","oxy-ou_minicart_mcsubt_margin_margin-top":"8","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-horizontal-offset":"0","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-vertical-offset":"0","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-blur":"16","oxy-ou_minicart_-widget-shopping-cart-content_box_shadow_box-shadow-color":"#e2e2e2","oxy-ou_minicart_remove_pright-unit":"%","oxy-ou_minicart_oumc_wrappermat":"30","oxy-ou_minicart_oumc_wrappermrt":"100","oxy-ou_minicart_oumc_wrappermrt-unit":"%","oxy-ou_minicart_oumc_wrappermlt":"-117","oxy-ou_minicart_remove_hc":"#ef0909","oxy-ou_minicart_cartbgns_width-unit":"%","oxy-ou_minicart_cartbgns_width":"100","oxy-ou_minicart_cartbgns_gap":"0","oxy-ou_minicart_cartbgns_gaptop":"10","oxy-ou_minicart_btn_align":"Left","oxy-ou_minicart_slug_ulcartlistliimgulproductlistwidgetliimg_border_width":"0","oxy-ou_minicart_itemimg_margin_margin-bottom":"0","oxy-ou_minicart_itemimg_margin_margin-top":"0","oxy-ou_minicart_oumc_prdimgw":"50","oxy-ou_minicart_remove_pright":"0","oxy-ou_minicart_mcitem_padding_padding-right":"20","oxy-ou_minicart_oumc_cprice":"yes"},"media":{"phone-landscape":{"original":{"oxy-ou_minicart_oumc_wrappermlt":"-120","oxy-ou_minicart_oumc_wrappermrt-unit":"%","oxy-ou_minicart_oumc_wrappermrt":"100"}}}}
			}',
			true
		)
	)
);